name: Build and Push Docker Image

# Se activará cuando se empujen cambios a la rama 'master'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verificar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: docker build . -t silenthill2024/calculadora-docker:latest

      # Paso 4: Iniciar sesión en Docker Hub y subir la imagen
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Paso 5: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push silenthill2024/calculadora-docker:latest
